### ISSUE TITLE
Selecting from the suggestions with touch pad adds element twice

### ISSUE THREAD

**Issue by technolion** [skalio/flutter-chips-selector#4]
Selecting from the suggestions with touch pad adds element twice. This only happens with the touchpad if you use the **_light tap_** - so not clicking the touch pad, but just lightly tapping it.

https://user-images.githubusercontent.com/1611505/222660378-46383b85-c938-4384-a639-7e6d354a9b31.mov

**Comment by technolion** [comment]
@jagmit @shrey112710 tested with Flutter 3.7.6 and spaces-frontend master from March 2nd 2023.

**Comment by technolion** [comment]
@ltOgt fyi

**Comment by jagmit** [comment]
Couldn't reproduce after the bigger refactor we did in https://github.com/skalio/flutter-chips-selector/pull/5. @technolion can you please check again?

**Comment by technolion** [comment]
I can confirm, that the issue is fixed. Thx guys!
